services:
  web:
    build: .
    container_name: dashboard-games-monitor
    env_file:
      - .env
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8003"
